name: CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  python-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Syntax check (compileall)
        run: python -m compileall -q .

      - name: Run pytest (if available)
        continue-on-error: true
        run: |
          if python -m pytest -q; then
            echo "pytest passed";
          else
            echo "pytest had failures or no tests ran; mark as allowed";
            exit 0;
          fi
