name: Integration tests (manual)

on:
  workflow_dispatch: {}

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system deps (Chromium)
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          sudo ln -sf /usr/lib/chromium-browser/chromedriver /usr/local/bin/chromedriver || true
        shell: bash

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
          # ensure pytest is available (requirements.txt may not list it)
          python -m pip install pytest -q

      - name: Start API server
        run: |
          # Start the FastAPI app (uvicorn) in background so integration scripts can talk to it
          nohup python -m uvicorn api:app --host 127.0.0.1 --port 8000 --log-level info > uvicorn.log 2>&1 &
          # Wait for the server to be reachable (timeout ~30s)
          for i in $(seq 1 30); do
            if curl -sS http://127.0.0.1:8000/docs >/dev/null 2>&1; then
              echo "api reachable"
              break
            fi
            sleep 1
          done
          echo "---- uvicorn.log (tail -n 200) ----"
          if [ -f uvicorn.log ]; then
            tail -n 200 uvicorn.log || true
          else
            echo "(no uvicorn.log found)"
          fi
          echo "---- process list for python/uvicorn ----"
          ps aux | egrep 'uvicorn|python' | egrep -v 'egrep' || true
          echo "---- listening TCP ports (ss -ltnp) ----"
          ss -ltnp 2>/dev/null || netstat -ltnp 2>/dev/null || true
        shell: bash

      - name: Run integration tests
        env:
          NAS_FOLDER: ${{ github.workspace }}
          CHROME_BIN: /usr/bin/chromium-browser
        run: |
          # Limit pytest collection to the tests/ directory to avoid collecting
          # same-named modules located elsewhere in the repo (which causes
          # 'import file mismatch' errors in CI).
          if [ -d tests ]; then
            # If there are integration_test_*.py scripts, run them directly
            scripts=$(ls tests/integration_test_*.py 2>/dev/null || true)
            if [ -n "$scripts" ]; then
              for s in $scripts; do
                echo "--- Running integration script: $s ---"
                python "$s"
              done
            else
              # Fallback: run any tests in tests/ that match the 'integration' keyword
              python -m pytest tests/ -q -k integration
            fi
          else
            # Fallback to previous behaviour if no tests/ directory exists
            python -m pytest -q -k integration
          fi

      - name: Collect server diagnostics
        if: always()
        run: |
          echo "---- process list for python/uvicorn ----" > server-diagnostics.txt
          ps aux | egrep 'uvicorn|python' | egrep -v 'egrep' >> server-diagnostics.txt || true
          echo "---- listening TCP ports (ss -ltnp / netstat) ----" >> server-diagnostics.txt
          ss -ltnp 2>/dev/null || netstat -ltnp 2>/dev/null || true >> server-diagnostics.txt
          echo "---- uvicorn.log (if present) ----" >> server-diagnostics.txt
          if [ -f uvicorn.log ]; then
            echo "(start of uvicorn.log)" >> server-diagnostics.txt
            tail -n 1000 uvicorn.log >> server-diagnostics.txt || true
            echo "(end of uvicorn.log)" >> server-diagnostics.txt
          else
            echo "(no uvicorn.log found)" >> server-diagnostics.txt
          fi
        shell: bash

      - name: Upload server diagnostics
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: server-diagnostics
          path: server-diagnostics.txt
