name: Integration tests (manual)

on:
  workflow_dispatch: {}

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system deps (Chromium)
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          sudo ln -sf /usr/lib/chromium-browser/chromedriver /usr/local/bin/chromedriver || true
        shell: bash

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
          # ensure pytest is available (requirements.txt may not list it)
          python -m pip install pytest -q

      - name: Run integration tests
        env:
          NAS_FOLDER: ${{ github.workspace }}
          CHROME_BIN: /usr/bin/chromium-browser
        run: |
          # Limit pytest collection to the tests/ directory to avoid collecting
          # same-named modules located elsewhere in the repo (which causes
          # 'import file mismatch' errors in CI).
          if [ -d tests ]; then
            # Prefer running files named integration_test_*.py to avoid relying on markers
            files=$(ls tests/integration_test_*.py 2>/dev/null || true)
            if [ -n "$files" ]; then
              python -m pytest $files -q
            else
              # Fallback: run any tests in tests/ that match the 'integration' keyword
              python -m pytest tests/ -q -k integration
            fi
          else
            # Fallback to previous behaviour if no tests/ directory exists
            python -m pytest -q -k integration
          fi
